// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20251107035655_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Entity.ForkEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Owner")
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("owner");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_ms");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "TimestampMs", "Index")
                        .IsUnique();

                    b.ToTable("fork_events", (string)null);
                });

            modelBuilder.Entity("Model.Entity.PhilosopherEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<int>("Eaten")
                        .HasColumnType("integer")
                        .HasColumnName("eaten");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<long>("RunId")
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<long>("TimestampMs")
                        .HasColumnType("bigint")
                        .HasColumnName("timestamp_ms");

                    b.Property<long>("WaitingTime")
                        .HasColumnType("bigint")
                        .HasColumnName("waiting_time");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "TimestampMs", "Index")
                        .IsUnique();

                    b.ToTable("philosopher_event", (string)null);
                });

            modelBuilder.Entity("Model.Entity.SimulationRun", b =>
                {
                    b.Property<long>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("run_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RunId"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int>("PhilosophersCount")
                        .HasColumnType("integer")
                        .HasColumnName("philosophers_count");

                    b.HasKey("RunId");

                    b.ToTable("simulation_run", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
